#ifndef TANGARA_TANGARADEFINES_HPP
#define TANGARA_TANGARADEFINES_HPP

#include "Entry.hpp"

#define TANGARA_INTERFACE(IName)
#define TANGARA_CLASS(ClassName)
#define TANGARA_METHOD(MethodName)
#define TANGARA_END()

#endif //TANGARA_TANGARADEFINES_HPP
